'use client';

import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Header } from '@/components/Header';
import { Hero } from '@/components/Hero';
import { UploadSection } from '@/components/UploadSection';
import { ScanAnimation } from '@/components/ScanAnimation';
import { ResultsDashboard } from '@/components/ResultsDashboard';
import { WorkflowTimeline } from '@/components/WorkflowTimeline';
import { DiseasesLibrary } from '@/components/DiseasesLibrary';
import { Features } from '@/components/Features';
import { FAQ } from '@/components/FAQ';
import { Testimonials } from '@/components/Testimonials';
import { Footer } from '@/components/Footer';

export default function Home() {
  const [selectedImage, setSelectedImage] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const [analysisResults, setAnalysisResults] = useState<any | null>(null);
  const [showNotification, setShowNotification] = useState(false);
  const [notificationMessage, setNotificationMessage] = useState('');
  const [apiError, setApiError] = useState<string | null>(null);

  const handleImageSelect = (file: File) => {
    setSelectedImage(file);
    const objectUrl = URL.createObjectURL(file);
    setImagePreview(objectUrl);
  };

  useEffect(() => {
    return () => {
      if (imagePreview?.startsWith('blob:')) {
        URL.revokeObjectURL(imagePreview);
      }
    };
  }, [imagePreview]);

  const normalizePrediction = (prediction: any) => {
    const rawConfidence = Number(prediction.confidence ?? 0.91);
    const confidence = rawConfidence > 1 ? rawConfidence / 100 : rawConfidence;
    const normalizedSeverity = ['mild', 'moderate', 'severe'].includes(prediction.severity)
      ? prediction.severity
      : 'moderate';

    return {
      condition: prediction.disease ?? prediction.condition ?? 'Eczema',
      confidence: Math.max(0, Math.min(1, confidence)),
      severity: normalizedSeverity,
      description:
        prediction.description ??
        'This prediction is generated by the backend placeholder service and is ready for future model integration.',
      recommendations: Array.isArray(prediction.recommendations)
        ? prediction.recommendations
        : [
            'Consult a dermatologist for professional evaluation',
            'Keep the affected area clean and monitor symptoms',
            'Use gentle skincare products until the diagnosis is confirmed',
          ],
    };
  };

  const handleAnalyzeStart = async () => {
    if (!selectedImage || !imagePreview) return;

    setIsAnalyzing(true);
    setShowResults(false);
    setApiError(null);

    const apiUrl = process.env.NEXT_PUBLIC_AI_API_URL ?? 'http://localhost:5000';
    const formData = new FormData();
    formData.append('file', selectedImage, selectedImage.name);

    try {
      const [prediction] = await Promise.all([
        fetch(`${apiUrl}/predict`, {
          method: 'POST',
          body: formData,
        }).then(async (res) => {
          if (!res.ok) {
            const errorPayload = await res.json().catch(() => null);
            const errorMessage = errorPayload?.error || res.statusText || `HTTP ${res.status}`;
            throw new Error(errorMessage);
          }
          return res.json();
        }),
        new Promise((resolve) => setTimeout(resolve, 3500)),
      ]);

      setAnalysisResults(normalizePrediction(prediction));
      setIsAnalyzing(false);
      setShowResults(true);
    } catch (error: any) {
      console.error('[Predict] error', error);
      const message = error?.message || 'Prediction request failed';
      setApiError(message);
      showAlert(`Prediction failed: ${message}`);
      setIsAnalyzing(false);
    }
  };

  const handleReset = () => {
    if (imagePreview?.startsWith('blob:')) {
      URL.revokeObjectURL(imagePreview);
    }
    setSelectedImage(null);
    setImagePreview(null);
    setIsAnalyzing(false);
    setShowResults(false);
    setAnalysisResults(null);
    setApiError(null);
  };

  const showAlert = (message: string) => {
    setNotificationMessage(message);
    setShowNotification(true);
    setTimeout(() => setShowNotification(false), 3000);
  };

  const handleStartTrial = () => {
    showAlert('Free trial signup - Redirecting to registration...');
    console.log('[v0] Start Free Trial clicked');
  };

  const handleGetStarted = () => {
    showAlert('Get Started - Connecting to onboarding flow...');
    console.log('[v0] Get Started clicked');
  };

  const handleScheduleDemo = () => {
    showAlert('Demo scheduled - Opening calendar...');
    console.log('[v0] Schedule Demo clicked');
  };

  const handleShareResults = () => {
    showAlert('Results copied to clipboard!');
    console.log('[v0] Share Results clicked');
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Notification Toast */}
      <AnimatePresence>
        {showNotification && (
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="fixed top-24 left-1/2 transform -translate-x-1/2 z-50 glass-card px-6 py-4 rounded-lg shadow-lg max-w-sm"
          >
            <p className="text-primary font-semibold text-center">{notificationMessage}</p>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Header */}
      <Header onStartTrial={handleStartTrial} />

      {/* Main Content */}
      <main className="pt-16">
        {/* Hero Section */}
        <Hero />

        {/* Upload & Analysis Section */}
        <section id="upload-section" className="py-20 px-4 sm:px-6 lg:px-8 bg-surface-container/30">
          <div className="max-w-6xl mx-auto">
            <AnimatePresence mode="wait">
              {!showResults && !isAnalyzing ? (
                <motion.div
                  key="upload"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="space-y-6"
                >
                  <UploadSection
                    onImageSelect={handleImageSelect}
                    onAnalyzeStart={handleAnalyzeStart}
                  />
                  {apiError && (
                    <motion.div
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="glass-card rounded-2xl p-6 border border-error/30 bg-error/10 text-error"
                    >
                      <p className="font-semibold mb-2">Prediction Error</p>
                      <p className="text-sm">{apiError}</p>
                    </motion.div>
                  )}
                </motion.div>
              ) : isAnalyzing ? (
                <motion.div
                  key="scanning"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="space-y-6"
                >
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="text-center mb-12"
                  >
                    <h2 className="text-4xl font-bold text-primary mb-4">Analyzing Your Image</h2>
                    <p className="text-on-surface-variant">
                      Our AI is processing your image with neural networks and computer vision algorithms...
                    </p>
                  </motion.div>
                  {imagePreview && <ScanAnimation imageUrl={imagePreview} isVisible={true} />}
                </motion.div>
              ) : (
                <motion.div
                  key="results"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="space-y-8"
                >
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="flex flex-col md:flex-row gap-8 items-start"
                  >
                    {/* Image Display */}
                    <motion.div
                      initial={{ opacity: 0, scale: 0.95 }}
                      animate={{ opacity: 1, scale: 1 }}
                      className="md:w-1/3"
                    >
                      <div className="glass-card rounded-2xl overflow-hidden aspect-video">
                        {imagePreview && (
                          <img
                            src={imagePreview}
                            alt="Analyzed"
                            className="w-full h-full object-contain"
                          />
                        )}
                      </div>
                    </motion.div>

                    {/* Results */}
                    <div className="md:w-2/3">
                      {analysisResults && (
                        <ResultsDashboard
                          prediction={analysisResults}
                          isVisible={showResults}
                        />
                      )}
                    </div>
                  </motion.div>

                  {/* Reset Button */}
                  <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.8 }}
                    className="flex gap-4"
                  >
                    <motion.button
                      onClick={handleReset}
                      className="flex-1 py-4 bg-secondary text-white font-semibold rounded-lg hover:bg-secondary-light transition-all hover:shadow-lg"
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      Analyze Another Image
                    </motion.button>
                    <motion.button
                      onClick={handleShareResults}
                      className="flex-1 py-4 glass-card text-primary font-semibold rounded-lg hover:bg-white/[0.12] transition-colors"
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      Share Results
                    </motion.button>
                  </motion.div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </section>

        {/* Workflow Timeline */}
        <div id="workflow">
          <WorkflowTimeline />
        </div>

        {/* Diseases Library */}
        <div id="diseases">
          <DiseasesLibrary />
        </div>

        {/* Features */}
        <div id="features">
          <Features />
        </div>

        {/* Testimonials */}
        <Testimonials />

        {/* FAQ */}
        <div id="faq">
          <FAQ />
        </div>

        {/* CTA Section Before Footer */}
        <section className="py-20 px-4 sm:px-6 lg:px-8 bg-gradient-to-b from-background to-primary">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="max-w-3xl mx-auto text-center text-white"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              Ready to Transform Your Dermatology Practice?
            </h2>
            <p className="text-xl text-white/80 mb-10">
              Join leading healthcare facilities using Stich AI for accurate, fast, and secure skin disease detection
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <motion.button
                onClick={handleGetStarted}
                className="px-8 py-4 bg-secondary text-primary font-semibold rounded-lg hover:bg-secondary-light transition-all hover:shadow-lg"
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
              >
                Get Started Today
              </motion.button>
              <motion.button
                onClick={handleScheduleDemo}
                className="px-8 py-4 border-2 border-white text-white font-semibold rounded-lg hover:bg-white/[0.1] transition-colors"
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
              >
                Schedule Demo
              </motion.button>
            </div>
          </motion.div>
        </section>
      </main>

      {/* Footer */}
      <Footer />
    </div>
  );
}
